class BookData:
    def __init__(self):
        self.book_data = [('All Flesh is Grass', 'Clifford D. Simak'), ('The Clone', 'Kate Wilhelm'),
     ('Dr. Bloodmoney, or How We Got Along After the Bomb', 'Philip K. Dick'), ('Dune', 'Frank Herbert'),
     ('The Escape Orbit', 'James White'), ('The Genocides', 'Thomas M. Disch'),
     ('Nova Express', 'William S. Burroughs'), ('A Plague of Demons', 'Keith Laumer'),
     ('Rogue Dragon', 'Avram Davidson'), ('The Ship That Sailed the Time Stream', 'G. C. Edmondson'),
     ('The Star Fox', 'Poul Anderson'), ('The Three Stigmata of Palmer Eldritch', 'Philip K. Dick'),
     ('Babel-17', 'Samuel R. Delany'), ('Flowers for Algernon', 'Daniel Keyes'),
     ('The Moon Is a Harsh Mistress', 'Robert A. Heinlein'), ('Chthon', 'Piers Anthony'),
     ('The Einstein Intersection', 'Samuel R. Delany'), ('The Eskimo Invasion', 'Hayden Howard'),
     ('Lord of Light', 'Roger Zelazny'), ('Thorns', 'Robert Silverberg'), ('Black Easter', 'James Blish'),
     ('Do Androids Dream of Electric Sheep?', 'Philip K. Dick'), ('The Masks of Time', 'Robert Silverberg'),
     ('Past Master', 'R. A. Lafferty'), ('Picnic on Paradise', 'Joanna Russ'), ('Rite of Passage', 'Alexei Panshin'),
     ('Stand on Zanzibar', 'John Brunner'), ('Bug Jack Barron', 'Norman Spinrad'),
     ('Isle of the Dead', 'Roger Zelazny'), ('The Jagged Orbit', 'John Brunner'),
     ('The Left Hand of Darkness', 'Ursula K. Le Guin'), ('Slaughterhouse-Five', 'Kurt Vonnegut'),
     ('Up the Line', 'Robert Silverberg'), ('And Chaos Died', 'Joanna Russ'), ('Fourth Mansions', 'R. A. Lafferty'),
     ('Ringworld', 'Larry Niven'), ('The Steel Crocodile', 'David G. Compton'), ('Tower of Glass', 'Robert Silverberg'),
     ('The Year of the Quiet Sun', 'Wilson Tucker'), ('The Byworlder', 'Poul Anderson'),
     ('The Devil is Dead', 'R. A. Lafferty'), ('Half Past Human', 'T. J. Bass'),
     ('The Lathe of Heaven', 'Ursula K. Le Guin'), ('Margaret and I', 'Kate Wilhelm'),
     ('A Time of Changes', 'Robert Silverberg'), ('The Book of Skulls', 'Robert Silverberg'),
     ('Dying Inside', 'Robert Silverberg'), ('The Gods Themselves', 'Isaac Asimov'),
     ('The Iron Dream', 'Norman Spinrad'), ('The Sheep Look Up', 'John Brunner'),
     ('What Entropy Means to Me', 'George Alec Effinger'), ('When HARLIE Was One', 'David Gerrold'),
     ("Gravity's Rainbow", 'Thomas Pynchon'), ('The Man Who Folded Himself', 'David Gerrold'),
     ('The People of the Wind', 'Poul Anderson'), ('Rendezvous with Rama', 'Arthur C. Clarke'),
     ('Time Enough for Love', 'Robert A. Heinlein'), ('334', 'Thomas M. Disch'),
     ('The Dispossessed', 'Ursula K. Le Guin'), ('Flow My Tears, the Policeman Said', 'Philip K. Dick'),
     ('The Godwhale', 'T. J. Bass'), ('Autumn Angels', 'Arthur Byron Cover'), ('The Birthgrave', 'Tanith Lee'),
     ('The Computer Connection', 'Alfred Bester'), ('Dhalgren', 'Samuel R. Delany'),
     ('Doorways in the Sand', 'Roger Zelazny'), ('The Embedding', 'Ian Watson'),
     ('The Exile Waiting', 'Vonda N. McIntyre'), ('The Female Man', 'Joanna Russ'), ('The Forever War', 'Joe Haldeman'),
     ('A Funeral for the Eyes of Fire', 'Michael Bishop'), ('Guernica Night', 'Barry N. Malzberg'),
     ('The Heritage of Hastur', 'Marion Zimmer Bradley'), ('Invisible Cities', 'Italo Calvino'),
     ('A Midsummer Tempest', 'Poul Anderson'), ('The Missing Man', 'Katherine MacLean'),
     ("The Mote in God's Eye", 'Larry Niven'), ("The Mote in God's Eye", 'Jerry Pournelle'),
     ('Ragtime', 'E. L. Doctorow'), ('The Stochastic Man', 'Robert Silverberg'), ('Inferno', 'Larry Niven'),
     ('Inferno', 'Jerry Pournelle'), ('Islands', 'Marta Randall'), ('Man Plus', 'Frederik Pohl'),
     ('Shadrach in the Furnace', 'Robert Silverberg'), ('Triton', 'Samuel R. Delany'),
     ('Where Late the Sweet Birds Sang', 'Kate Wilhelm'), ('Cirque', 'Terry Carr'), ('Gateway', 'Frederik Pohl'),
     ('In the Ocean of Night', 'Gregory Benford'), ('Moonstar Odyssey', 'David Gerrold'),
     ('Sword of the Demon', 'Richard A. Lupoff'), ('Blind Voices', 'Tom Reamy'), ('Dreamsnake', 'Vonda N. McIntyre'),
     ('The Faded Sun: Kesrith', 'C. J. Cherryh'), ('Kalki', 'Gore Vidal'), ('Strangers', 'Gardner Dozois'),
     ('The Fountains of Paradise', 'Arthur C. Clarke'), ('Jem', 'Frederik Pohl'), ('Juniper Time', 'Kate Wilhelm'),
     ('On Wings of Song', 'Thomas M. Disch'), ('The Road to Corlay', 'Richard Cowper'), ('Titan', 'John Varley'),
     ('Beyond the Blue Event Horizon', 'Frederik Pohl'), ('Mockingbird', 'Walter Tevis'),
     ('The Orphan', 'Robert Stallman'), ('The Shadow of the Torturer', 'Gene Wolfe'),
     ('The Snow Queen', 'Joan D. Vinge'), ('Timescape', 'Gregory Benford'),
     ('The Claw of the Conciliator', 'Gene Wolfe'), ('Little, Big', 'John Crowley'),
     ('The Many-Colored Land', 'Julian May'), ('Radix', 'A. A. Attanasio'), ('Riddley Walker', 'Russell Hoban'),
     ('The Vampire Tapestry', 'Suzy McKee Charnas'), ("Foundation's Edge", 'Isaac Asimov'),
     ('Friday', 'Robert A. Heinlein'), ('Helliconia Spring', 'Brian Aldiss'), ('No Enemy But Time', 'Michael Bishop'),
     ('The Sword of the Lictor', 'Gene Wolfe'), ('The Transmigration of Timothy Archer', 'Philip K. Dick'),
     ('Against Infinity', 'Gregory Benford'), ('The Citadel of the Autarch', 'Gene Wolfe'), ('Lyonesse', 'Jack Vance'),
     ('Startide Rising', 'David Brin'), ('Tea with the Black Dragon', 'R. A. MacAvoy'),
     ("The Void Captain's Tale", 'Norman Spinrad'), ('Frontera', 'Lewis Shiner'), ('The Integral Trees', 'Larry Niven'),
     ('Job: A Comedy of Justice', 'Robert A. Heinlein'), ('The Man Who Melted', 'Jack Dann'),
     ('Neuromancer', 'William Gibson'), ('The Wild Shore', 'Kim Stanley Robinson'), ('Blood Music', 'Greg Bear'),
     ("Dinner at Deviant's Palace", 'Tim Powers'), ("Ender's Game", 'Orson Scott Card'),
     ('Helliconia Winter', 'Brian Aldiss'), ('The Postman', 'David Brin'),
     ('The Remaking of Sigmund Freud', 'Barry N. Malzberg'), ('Schismatrix', 'Bruce Sterling'),
     ('Count Zero', 'William Gibson'), ('Free Live Free', 'Gene Wolfe'), ("The Handmaid's Tale", 'Margaret Atwood'),
     ('The Journal of Nicholas the American', 'Leigh Kennedy'), ('Speaker for the Dead', 'Orson Scott Card'),
     ('This is the Way the World Ends', 'James K. Morrow'), ('The Falling Woman', 'Pat Murphy'),
     ('The Forge of God', 'Greg Bear'), ('Soldier of the Mist', 'Gene Wolfe'), ('The Uplift War', 'David Brin'),
     ('Vergil in Averno', 'Avram Davidson'), ('When Gravity Fails', 'George Alec Effinger'),
     ('Deserted Cities of the Heart', 'Lewis Shiner'), ('Drowning Towers', 'George Turner'),
     ('Falling Free', 'Lois McMaster Bujold'), ('Great Sky River', 'Gregory Benford'),
     ('Mona Lisa Overdrive', 'William Gibson'), ('Red Prophet', 'Orson Scott Card'),
     ('The Urth of the New Sun', 'Gene Wolfe'), ('The Boat of a Million Years', 'Poul Anderson'),
     ('Good News From Outer Space', 'John Kessel'), ("The Healer's War", 'Elizabeth Ann Scarborough'),
     ('Ivory: A Legend of Past and Future', 'Mike Resnick'), ('Prentice Alvin', 'Orson Scott Card'),
     ('Sister Light, Sister Dark', 'Jane Yolen'), ('The Fall of Hyperion', 'Dan Simmons'),
     ('Tehanu: The Last Book of Earthsea', 'Ursula K. Le Guin'), ('Mary Reilly', 'Valerie Martin'),
     ('Only Begotten Daughter', 'James K. Morrow'), ('Redshift Rendezvous', 'John E. Stith'),
     ('White Jenna', 'Jane Yolen'), ('Barrayar', 'Lois McMaster Bujold'), ('Bone Dance', 'Emma Bull'),
     ('The Difference Engine', 'Bruce Sterling'), ('The Difference Engine', 'William Gibson'),
     ('Orbital Resonance', 'John Barnes'), ('Stations of the Tide', 'Michael Swanwick'), ('Synners', 'Pat Cadigan'),
     ('Briar Rose', 'Jane Yolen'), ('China Mountain Zhang', 'Maureen F. McHugh'), ('Doomsday Book', 'Connie Willis'),
     ('A Fire Upon the Deep', 'Vernor Vinge'), ('A Million Open Doors', 'John Barnes'),
     ('Sarah Canary', 'Karen Joy Fowler'), ('Assemblers of Infinity', 'Kevin J. Anderson'),
     ('Assemblers of Infinity', 'Doug Beason'), ('Beggars in Spain', 'Nancy Kress'), ('Hard Landing', 'Algis Budrys'),
     ('Nightside the Long Sun', 'Gene Wolfe'), ('Red Mars', 'Kim Stanley Robinson'),
     ('Green Mars', 'Kim Stanley Robinson'), ('Gun, with Occasional Music', 'Jonathan Lethem'),
     ('Moving Mars', 'Greg Bear'), ('A Night in the Lonesome October', 'Roger Zelazny'),
     ('Parable of the Sower', 'Octavia E. Butler'), ('Temporary Agency', 'Rachel Pollack'),
     ('Towing Jehovah', 'James K. Morrow'), ('Beggars and Choosers', 'Nancy Kress'),
     ('Calde of the Long Sun', 'Gene Wolfe'), ('Celestis', 'Paul Park'), ('Metropolitan', 'Walter Jon Williams'),
     ('Mother of Storms', 'John Barnes'), ('The Terminal Experiment', 'Robert J. Sawyer'),
     ('The Diamond Age', 'Neal Stephenson'), ('Expiration Date', 'Tim Powers'),
     ('The Silent Strength of Stones', 'Nina Kiriki Hoffman'), ('Slow River', 'Nicola Griffith'),
     ('Starplex', 'Robert J. Sawyer'), ('Winter Rose', 'Patricia A. McKillip'), ('Ancient Shores', 'Jack McDevitt'),
     ('Bellwether', 'Connie Willis'), ('City on Fire', 'Walter Jon Williams'),
     ('A Game of Thrones', 'George R. R. Martin'), ("King's Dragon", 'Kate Elliott'),
     ('Memory', 'Lois McMaster Bujold'), ('The Moon and the Sun', 'Vonda N. McIntyre'),
     ('Forever Peace', 'Joe Haldeman'), ('How Few Remain', 'Harry Turtledove'), ('The Last Hawk', 'Catherine Asaro'),
     ('Moonfall', 'Jack McDevitt'), ('The Death of the Necromancer', 'Martha Wells'),
     ('To Say Nothing of the Dog', 'Connie Willis'), ('The Cassini Division', 'Ken MacLeod'),
     ('A Clash of Kings', 'George R. R. Martin'), ('A Deepness in the Sky', 'Vernor Vinge'),
     ('Mission Child', 'Maureen F. McHugh'), ('Mockingbird', 'Sean Stewart'),
     ('Parable of the Talents', 'Octavia E. Butler'), ('A Civil Campaign', 'Lois McMaster Bujold'),
     ('Crescent City Rhapsody', 'Kathleen Ann Goonan'), ("Darwin's Radio", 'Greg Bear'),
     ('Forests of the Heart', 'Charles de Lint'), ('Infinity Beach', 'Jack McDevitt'),
     ('Midnight Robber', 'Nalo Hopkinson'), ('The Collapsium', 'Wil McCarthy'), ('Declare', 'Tim Powers'),
     ("Eternity's End", 'Jeffrey Carver'), ('Mars Crossing', 'Geoffrey A. Landis'), ('Passage', 'Connie Willis'),
     ('The Quantum Rose', 'Catherine Asaro'), ('A Storm of Swords', 'George R. R. Martin'),
     ('The Tower at Stony Wood', 'Patricia A. McKillip'), ('American Gods', 'Neil Gaiman'),
     ('Bones of the Earth', 'Michael Swanwick'), ('The Other Wind', 'Ursula K. Le Guin'),
     ('Perdido Street Station', 'China MiÃ©ville'), ('Picoverse', 'Robert A. Metzger'),
     ('Solitaire', 'Kelley Eskridge'), ('Chindi', 'Jack McDevitt'), ('Diplomatic Immunity', 'Lois McMaster Bujold'),
     ('Light Music', 'Kathleen Ann Goonan'), ('The Mount', 'Carol Emshwiller'), ('The Salt Roads', 'Nalo Hopkinson'),
     ('The Speed of Dark', 'Elizabeth Moon'), ('Cloud Atlas', 'David Mitchell'),
     ('Down and Out in the Magic Kingdom', 'Cory Doctorow'), ('The Knight', 'Gene Wolfe'), ('Omega', 'Jack McDevitt'),
     ('Paladin of Souls', 'Lois McMaster Bujold'), ('Perfect Circle', 'Sean Stewart'), ('Air', 'Geoff Ryman'),
     ('Camouflage', 'Joe Haldeman'), ('Going Postal', 'Terry Pratchett'),
     ('Jonathan Strange & Mr Norrell', 'Susanna Clarke'), ('Orphans of Chaos', 'John C. Wright'),
     ('Polaris', 'Jack McDevitt'), ('Farthing', 'Jo Walton'), ('From the Files of the Time Rangers', 'Richard Bowes'),
     ('The Girl in the Glass', 'Jeffrey Ford'), ('The Privilege of the Sword', 'Ellen Kushner'),
     ('Seeker', 'Jack McDevitt'), ('To Crush the Moon', 'Wil McCarthy'),
     ('The Accidental Time Machine', 'Joe Haldeman'), ("The New Moon's Arms", 'Nalo Hopkinson'),
     ('Odyssey', 'Jack McDevitt'), ('Ragamuffin', 'Tobias S. Buckell'),
     ("The Yiddish Policemen's Union", 'Michael Chabon'), ('Brasyl', 'Ian McDonald'), ('Cauldron', 'Jack McDevitt'),
     ('Little Brother', 'Cory Doctorow'), ('Making Money', 'Terry Pratchett'), ('Powers', 'Ursula K. Le Guin'),
     ('Superpowers', 'David J. Schwartz'), ('Boneshaker', 'Cherie Priest'), ('The City & the City', 'China MiÃ©ville'),
     ('Finch', 'Jeff VanderMeer'), ('Flesh and Fire', 'Laura Anne Gilman'),
     ('The Love We Share Without Knowing', 'Christopher Barzak'), ('The Windup Girl', 'Paolo Bacigalupi'),
     ('Blackout/All Clear', 'Connie Willis'), ('Echo', 'Jack McDevitt'),
     ('The Hundred Thousand Kingdoms', 'N. K. Jemisin'), ('The Native Star', 'M. K. Hobson'),
     ('Shades of Milk and Honey', 'Mary Robinette Kowal'), ('Who Fears Death', 'Nnedi Okorafor'),
     ('Among Others', 'Jo Walton'), ('Embassytown', 'China MiÃ©ville'), ('Firebird', 'Jack McDevitt'),
     ("God's War", 'Kameron Hurley'), ('The Kingdom of Gods', 'N. K. Jemisin'),
     ('Mechanique: a Tale of the Circus Tresaulti', 'Genevieve Valentine'), ('2312', 'Kim Stanley Robinson'),
     ('Glamour in Glass', 'Mary Robinette Kowal'), ('Ironskin', 'Tina Connolly'),
     ('The Drowning Girl', 'CaitlÃ\xadn R. Kiernan'), ('The Killing Moon', 'N. K. Jemisin'),
     ('Throne of the Crescent Moon', 'Saladin Ahmed'), ('A Stranger in Olondria', 'Sofia Samatar'),
     ('Ancillary Justice', 'Ann Leckie'), ('Fire with Fire', 'Charles E. Gannon'),
     ('The Golem and the Jinni', 'Helene Wecker'), ('Hild', 'Nicola Griffith'),
     ('The Ocean at the End of the Lane', 'Neil Gaiman'), ('The Red: First Light', 'Linda Nagata'),
     ('We Are All Completely Beside Ourselves', 'Karen Joy Fowler'), ('Ancillary Sword', 'Ann Leckie'),
     ('Annihilation', 'Jeff VanderMeer'), ('Coming Home', 'Jack McDevitt'), ('The Goblin Emperor', 'Katherine Addison'),
     ('The Three-Body Problem', 'Cixin Liu'), ('Trial by Fire', 'Charles E. Gannon'), ('Ancillary Mercy', 'Ann Leckie'),
     ("Barsk: The Elephants' Graveyard", 'Lawrence M. Schoen'), ('The Fifth Season', 'N. K. Jemisin'),
     ('The Grace of Kings', 'Ken Liu'), ('Raising Caine', 'Charles E. Gannon'), ('Updraft', 'Fran Wilde'),
     ('Uprooted', 'Naomi Novik'), ('All the Birds in the Sky', 'Charlie Jane Anders'), ('Borderline', 'Mishell Baker'),
     ('Everfair', 'Nisi Shawl'), ('Ninefox Gambit', 'Yoon Ha Lee'), ('The Obelisk Gate', 'N. K. Jemisin'),
     ('Amberlough', 'Lara Elena Donnelly'), ('Autonomous', 'Annalee Newitz'), ('Jade City', 'Fonda Lee'),
     ('Six Wakes', 'Mur Lafferty'), ('Spoonbenders', 'Daryl Gregory'), ('The Stone Sky', 'N. K. Jemisin'),
     ("The Strange Case of the Alchemist's Daughter", 'Theodora Goss'), ('Blackfish City', 'Sam J. Miller'),
     ('The Calculating Stars', 'Mary Robinette Kowal'), ('The Poppy War', 'R. F. Kuang'),
     ('Spinning Silver', 'Naomi Novik'), ('Trail of Lightning', 'Rebecca Roanhorse'), ('Witchmark', 'C. L. Polk'),
     ('Gideon the Ninth', 'Tamsyn Muir'), ('Gods of Jade and Shadow', 'Silvia Moreno-Garcia'),
     ('Marque of Caine', 'Charles E. Gannon'), ('A Memory Called Empire', 'Arkady Martine'),
     ('A Song for a New Day', 'Sarah Pinsker'), ('The Ten Thousand Doors of January', 'Alix E. Harrow'),
     ('Black Sun', 'Rebecca Roanhorse'), ('The City We Became', 'N. K. Jemisin'),
     ('Mexican Gothic', 'Silvia Moreno-Garcia'), ('The Midnight Bargain', 'C. L. Polk'),
     ('Network Effect', 'Martha Wells'), ('Piranesi', 'Susanna Clarke'),
     ('A Desolation Called Peace', 'Arkady Martine'), ('Machinehood', 'S. B. Divya'),
     ('A Master of Djinn', 'P. DjÃ¨lÃ\xad Clark'), ('Plague Birds', 'Jason Sanford'), ('The Unbroken', 'C. L. Clark')]


